repos:
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
